CREATE INDEX idx_tickets_ticket_no_id_name ON Tickets(ticket_no, passenger_id, passenger_name);
CREATE INDEX idx_ticket_flights_ticket_no_flight_id ON Ticket_flights(ticket_no, flight_id);
CREATE INDEX idx_flights_flight_id_dep_arr_aircraft_sched ON Flights(flight_id, departure_airport, arrival_airport, aircraft_code, scheduled_departure, scheduled_arrival);
CREATE INDEX idx_airports_data_code_name ON airports_data(airport_code, airport_name);
CREATE INDEX idx_aircrafts_data_code_model ON aircrafts_data(aircraft_code, model);
CREATE INDEX idx_flights_arrival_sched ON flights(arrival_airport, scheduled_arrival);
CREATE INDEX idx_flights_scheduled_arrival_desc ON flights(scheduled_arrival DESC);
CREATE INDEX idx_aircrafts_code_model ON aircrafts_data(aircraft_code, model);
CREATE INDEX idx_airports_code_city ON airports_data(airport_code, city);
CREATE INDEX idx_flights_sched_arrival ON flights(scheduled_arrival);
CREATE INDEX idx_ticket_flights_join ON Ticket_flights(ticket_no, flight_id);
CREATE INDEX idx_boarding_passes_join ON Boarding_passes(ticket_no, flight_id) 
INCLUDE (seat_no);
CREATE INDEX idx_flights_scheduled_arr ON Flights(scheduled_arrival DESC) 
INCLUDE (flight_id, flight_no, scheduled_departure, departure_airport, arrival_airport, aircraft_code);
CREATE INDEX idx_flights_route_timing ON Flights(departure_airport, scheduled_departure) 
INCLUDE (arrival_airport, scheduled_arrival);
CREATE INDEX idx_flights_departure_airport ON flights(departure_airport);
CREATE INDEX idx_flights_arrival_airport ON flights(arrival_airport);
CREATE INDEX idx_flights_scheduled_departure ON flights(scheduled_departure);
CREATE INDEX idx_flights_status ON flights(status);
CREATE INDEX idx_flights_route_time ON flights(departure_airport, arrival_airport, scheduled_departure);
CREATE INDEX idx_ticket_flights_flight_id ON ticket_flights(flight_id);
CREATE INDEX idx_ticket_flights_fare_conditions ON ticket_flights(fare_conditions);
CREATE INDEX idx_boarding_passes_flight_id ON boarding_passes(flight_id);
CREATE INDEX idx_boarding_passes_ticket_no ON boarding_passes(ticket_no);
CREATE INDEX idx_seats_aircraft_code ON seats(aircraft_code);
CREATE INDEX idx_seats_fare_conditions ON seats(fare_conditions);
CREATE INDEX idx_aircrafts_data_aircraft_code ON aircrafts_data(aircraft_code);
CREATE INDEX idx_airports_data_code ON airports_data(airport_code);
CREATE INDEX idx_flights_scheduled_arrival ON flights(scheduled_arrival);
CREATE INDEX idx_ticket_flights_flight_id_fare_conditions ON ticket_flights(flight_id, fare_conditions);
CREATE INDEX idx_seats_aircraft_code_fare_conditions ON seats(aircraft_code, fare_conditions);
CREATE INDEX idx_flights_dep_status_sched ON flights(departure_airport, status, scheduled_departure);
CREATE INDEX idx_flights_dep_sched ON flights(departure_airport, scheduled_departure);
CREATE INDEX idx_flights_dep_arr_status_sched ON flights(departure_airport, arrival_airport, status, scheduled_departure);
CREATE INDEX idx_flights_dep_sched_status ON flights(departure_airport, scheduled_departure, status);
CREATE INDEX idx_ticket_flights_fare_flight_amount ON ticket_flights(flight_id, fare_conditions) INCLUDE (amount);
CREATE INDEX idx_flights_dep_arr_sched ON flights(departure_airport, arrival_airport, scheduled_departure);
CREATE INDEX idx_boarding_passes_flight_ticket ON boarding_passes(flight_id, ticket_no);
CREATE INDEX idx_flights_dep_arr_actual ON flights(departure_airport, arrival_airport, actual_arrival, scheduled_departure);
CREATE INDEX idx_flights_flight_id_aircraft ON flights(flight_id) INCLUDE (aircraft_code);
CREATE INDEX idx_tickets_ticket_no_name_id ON tickets(ticket_no, passenger_name, passenger_id);
CREATE INDEX idx_tickets_passenger_grp_inc ON tickets(passenger_name, passenger_id) INCLUDE (ticket_no);
CREATE INDEX idx_ticket_flights_ticket_no_flight_id_amount ON ticket_flights(ticket_no, flight_id, amount);
CREATE INDEX idx_tf_ticket_flight_amount ON ticket_flights(ticket_no, flight_id) INCLUDE (amount);
CREATE INDEX idx_flights_flight_id_aircraft_code_departure ON flights(flight_id, aircraft_code, actual_departure);
CREATE INDEX idx_flights_actual_dep_inc ON flights(actual_departure) INCLUDE (flight_id, aircraft_code);
CREATE INDEX idx_flights_flight_id_actual ON flights(flight_id, actual_departure);
CREATE INDEX idx_flights_aircraft_code_inc ON flights(aircraft_code) INCLUDE (flight_id);
CREATE INDEX idx_boarding_passes_ticket_no_flight_id_seat_no ON boarding_passes(ticket_no, flight_id, seat_no);
CREATE INDEX idx_aircrafts_code_inc_model ON aircrafts_data(aircraft_code) INCLUDE (model);
CREATE INDEX idx_tickets_book_ref ON tickets(book_ref);
CREATE INDEX idx_airports_airport_code ON airports_data(airport_code);
CREATE INDEX idx_ticket_flights_amount ON ticket_flights(amount);
CREATE INDEX idx_ticket_flights_flight_id_amount ON ticket_flights(flight_id, amount);
CREATE INDEX idx_ticket_flights_total_amount ON ticket_flights(amount DESC);
CREATE INDEX idx_ticket_flights_num_flights ON ticket_flights(flight_id DESC);
CREATE INDEX idx_flights_airports ON flights(departure_airport, arrival_airport);
CREATE INDEX idx_bookings_book_ref ON bookings(book_ref);
CREATE INDEX idx_tickets_book_ref_ticket_no ON tickets(book_ref, ticket_no);